debug: false
management.endpoints.web.exposure.include: "*"

# 서버 설정
server:
  port: 443
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: rlaxogjs8312


logging:
  level:
    com.wit.com.wit.unifesta: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  # 데이터베이스 설정
  datasource:
#    url: jdbc:mysql://52.78.59.88:3306/unifesta
#    username: jakeheon
#    password: rlaxogjs8312@
    url: jdbc:mysql://localhost:3306/unifesta
    username: root
    password: rlaxogjs8312@
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    driver-class-name: org.h2.Driver
  # jpa 설정
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  h2:
    console:
      enabled: false
  sql:
    init:
      mode: always
      platform: mysql
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 613126198444-jc1k12sumj8fk5afc1846b0pmem1k3lh.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile


---

spring:
  config:
    activate:
      on-profile: testdb
  datasource:
    url: jdbc:h2:mem:unifesta;mode=mysql
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
  test.database.replace: none
  thymeleaf3:
    decoupled-logic: true

