spring:
  config:
    activate:
      on-profile: @spring.profiles.active@

# 서버 설정
server:
  port: 5000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8

app:
  datasource:
    jdbc-url: jdbc:mysql://unifesta.c9pavs7woqch.ap-northeast-2.rds.amazonaws.com:3306/unifesta
    username: jakeheon
    password: rlaxogjs8312@
    pool-size: 30
