debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.wit.com.wit.unifesta: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  # 데이터베이스 설정
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: taeheon
    password: rlaxogjs8312@
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    driver-class-name: org.h2.Driver
  # jpa 설정
  jpa:
    open-in-view: true
    database-platform:
      org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
  data:
    rest:
      base-path: /
      detection-strategy: annotated
---

spring:
  config:
    activate:
      on-profile: testdb
  datasource:
    url: jdbc:h2:mem:board;mode=mysql
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
  test.database.replace: none
#  thymeleaf3:
#    decoupled-logic: true